In [ ]:
import pandas as pd
import matplotlib.pyplot as plt

from sklearn import datasets
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import  DecisionTreeClassifier
from sklearn import tree
from sklearn.metrics import classification_report
from sklearn import preprocessing

In [ ]:
data = pd.read_csv("https://raw.githubusercontent.com/slmsshk/DataSet/main/penguins.csv")

In [ ]:
data.info

<bound method DataFrame.info of     species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0    Adelie  Torgersen            39.1           18.7              181.0   
1    Adelie  Torgersen            39.5           17.4              186.0   
2    Adelie  Torgersen            40.3           18.0              195.0   
3    Adelie  Torgersen             NaN            NaN                NaN   
4    Adelie  Torgersen            36.7           19.3              193.0   
..      ...        ...             ...            ...                ...   
339  Gentoo     Biscoe             NaN            NaN                NaN   
340  Gentoo     Biscoe            46.8           14.3              215.0   
341  Gentoo     Biscoe            50.4           15.7              222.0   
342  Gentoo     Biscoe            45.2           14.8              212.0   
343  Gentoo     Biscoe            49.9           16.1              213.0   

     body_mass_g     sex  
0         3750.0    MALE  
1

In [ ]:
data

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0    Adelie  Torgersen            39.1           18.7              181.0   
1    Adelie  Torgersen            39.5           17.4              186.0   
2    Adelie  Torgersen            40.3           18.0              195.0   
3    Adelie  Torgersen             NaN            NaN                NaN   
4    Adelie  Torgersen            36.7           19.3              193.0   
..      ...        ...             ...            ...                ...   
339  Gentoo     Biscoe             NaN            NaN                NaN   
340  Gentoo     Biscoe            46.8           14.3              215.0   
341  Gentoo     Biscoe            50.4           15.7              222.0   
342  Gentoo     Biscoe            45.2           14.8              212.0   
343  Gentoo     Biscoe            49.9           16.1              213.0   

     body_mass_g     sex  
0         3750.0    MALE  
1         3800.0  FEMALE  
2         3250.0  FEMALE  
3            NaN     NaN  
4         3450.0  FEMALE  
..           ...     ...  
339          NaN     NaN  
340       4850.0  FEMALE  
341       5750.0    MALE  
342       5200.0  FEMALE  
343       5400.0    MALE  

[344 rows x 7 columns]

In [ ]:
data.head()

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7              181.0   
1  Adelie  Torgersen            39.5           17.4              186.0   
2  Adelie  Torgersen            40.3           18.0              195.0   
3  Adelie  Torgersen             NaN            NaN                NaN   
4  Adelie  Torgersen            36.7           19.3              193.0   

   body_mass_g     sex  
0       3750.0    MALE  
1       3800.0  FEMALE  
2       3250.0  FEMALE  
3          NaN     NaN  
4       3450.0  FEMALE

In [ ]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

In [ ]:
# creating instance of one hot encoder
OHE = OneHotEncoder(handle_unknown='ignore')

In [ ]:
data[['island']]

island
0    Torgersen
1    Torgersen
2    Torgersen
3    Torgersen
4    Torgersen
..         ...
339     Biscoe
340     Biscoe
341     Biscoe
342     Biscoe
343     Biscoe

[344 rows x 1 columns]

In [ ]:
island=OHE.fit_transform(data[['island']]).toarray()

In [ ]:
island

array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       ...,
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [ ]:
sex=OHE.fit_transform(data[['sex']]).toarray()

In [ ]:
sex

array([[0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       ...,
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [ ]:
LE= LabelEncoder()
data['species']=LE.fit_transform(data['species'])

In [ ]:
data.head()

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0        0  Torgersen            39.1           18.7              181.0   
1        0  Torgersen            39.5           17.4              186.0   
2        0  Torgersen            40.3           18.0              195.0   
3        0  Torgersen             NaN            NaN                NaN   
4        0  Torgersen            36.7           19.3              193.0   

   body_mass_g     sex  
0       3750.0    MALE  
1       3800.0  FEMALE  
2       3250.0  FEMALE  
3          NaN     NaN  
4       3450.0  FEMALE

In [ ]:
data.species.value_counts()

0    152
2    124
1     68
Name: species, dtype: int64

In [ ]:
df=pd.get_dummies(data)
df.head()

species  bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g  \
0        0            39.1           18.7              181.0       3750.0   
1        0            39.5           17.4              186.0       3800.0   
2        0            40.3           18.0              195.0       3250.0   
3        0             NaN            NaN                NaN          NaN   
4        0            36.7           19.3              193.0       3450.0   

   island_Biscoe  island_Dream  island_Torgersen  sex_FEMALE  sex_MALE  
0              0             0                 1           0         1  
1              0             0                 1           1         0  
2              0             0                 1           1         0  
3              0             0                 1           0         0  
4              0             0                 1           1         0

IsolationForest

In [ ]:
from sklearn.ensemble import IsolationForest
import pandas as pd

In [ ]:
data =pd.read_csv("https://raw.githubusercontent.com/slmsshk/DataSet/main/iris.csv")
data_encoded=pd.get_dummies(data)

In [ ]:
data_encoded

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width  Species_setosa  \
0             5.1          3.5           1.4          0.2               1   
1             4.9          3.0           1.4          0.2               1   
2             4.7          3.2           1.3          0.2               1   
3             4.6          3.1           1.5          0.2               1   
4             5.0          3.6           1.4          0.2               1   
..            ...          ...           ...          ...             ...   
145           6.7          3.0           5.2          2.3               0   
146           6.3          2.5           5.0          1.9               0   
147           6.5          3.0           5.2          2.0               0   
148           6.2          3.4           5.4          2.3               0   
149           5.9          3.0           5.1          1.8               0   

     Species_versicolor  Species_virginica  
0                     0                  0  
1                     0                  0  
2                     0                  0  
3                     0                  0  
4                     0                  0  
..                  ...                ...  
145                   0                  1  
146                   0                  1  
147                   0                  1  
148                   0                  1  
149                   0                  1  

[150 rows x 7 columns]

In [ ]:
# training the model
clf = IsolationForest(random_state=10,contamination=.01)
clf.fit(data_encoded)

IsolationForest(contamination=0.01, random_state=10)

In [ ]:
# predictions
y_pred_outliers = clf.predict(data_encoded)

In [ ]:
#-1 for outliers and 1 for inliers.
y_pred_outliers

array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1])

In [ ]:
data_encoded


Sepal.Length  Sepal.Width  Petal.Length  Petal.Width  Species_setosa  \
0             5.1          3.5           1.4          0.2               1   
1             4.9          3.0           1.4          0.2               1   
2             4.7          3.2           1.3          0.2               1   
3             4.6          3.1           1.5          0.2               1   
4             5.0          3.6           1.4          0.2               1   
..            ...          ...           ...          ...             ...   
145           6.7          3.0           5.2          2.3               0   
146           6.3          2.5           5.0          1.9               0   
147           6.5          3.0           5.2          2.0               0   
148           6.2          3.4           5.4          2.3               0   
149           5.9          3.0           5.1          1.8               0   

     Species_versicolor  Species_virginica  
0                     0                  0  
1                     0                  0  
2                     0                  0  
3                     0                  0  
4                     0                  0  
..                  ...                ...  
145                   0                  1  
146                   0                  1  
147                   0                  1  
148                   0                  1  
149                   0                  1  

[150 rows x 7 columns]

In [ ]:
## Let us add a new data point which is outlier
data_encoded.loc[150]=[20,40,30,50,1,0,0]

In [ ]:
data_encoded


Sepal.Length  Sepal.Width  Petal.Length  Petal.Width  Species_setosa  \
0             5.1          3.5           1.4          0.2               1   
1             4.9          3.0           1.4          0.2               1   
2             4.7          3.2           1.3          0.2               1   
3             4.6          3.1           1.5          0.2               1   
4             5.0          3.6           1.4          0.2               1   
..            ...          ...           ...          ...             ...   
146           6.3          2.5           5.0          1.9               0   
147           6.5          3.0           5.2          2.0               0   
148           6.2          3.4           5.4          2.3               0   
149           5.9          3.0           5.1          1.8               0   
150          20.0         40.0          30.0         50.0               1   

     Species_versicolor  Species_virginica  
0                     0                  0  
1                     0                  0  
2                     0                  0  
3                     0                  0  
4                     0                  0  
..                  ...                ...  
146                   0                  1  
147                   0                  1  
148                   0                  1  
149                   0                  1  
150                   0                  0  

[151 rows x 7 columns]

In [ ]:
# training the model
clf = IsolationForest(random_state=10,contamination=.01)
clf.fit(data_encoded)
# predictions
y_pred_outliers = clf.predict(data_encoded)
y_pred_outliers

array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1])

In [ ]:
data_encoded['scores']=clf.decision_function(data_encoded)

In [ ]:
data_encoded['anomaly']=clf.predict(data_encoded.iloc[:,0:7])

In [ ]:
data_encoded

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width  Species_setosa  \
0             5.1          3.5           1.4          0.2               1   
1             4.9          3.0           1.4          0.2               1   
2             4.7          3.2           1.3          0.2               1   
3             4.6          3.1           1.5          0.2               1   
4             5.0          3.6           1.4          0.2               1   
..            ...          ...           ...          ...             ...   
146           6.3          2.5           5.0          1.9               0   
147           6.5          3.0           5.2          2.0               0   
148           6.2          3.4           5.4          2.3               0   
149           5.9          3.0           5.1          1.8               0   
150          20.0         40.0          30.0         50.0               1   

     Species_versicolor  Species_virginica    scores  anomaly  
0                     0                  0  0.201438        1  
1                     0                  0  0.183516        1  
2                     0                  0  0.173272        1  
3                     0                  0  0.181867        1  
4                     0                  0  0.198218        1  
..                  ...                ...       ...      ...  
146                   0                  1  0.134374        1  
147                   0                  1  0.178850        1  
148                   0                  1  0.122817        1  
149                   0                  1  0.156061        1  
150                   0                  0 -0.287729       -1  

[151 rows x 9 columns]

In [ ]:
#Print the outlier data points
data_encoded[data_encoded['anomaly']==-1]

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width  Species_setosa  \
106           4.9          2.5           4.5          1.7               0   
150          20.0         40.0          30.0         50.0               1   

     Species_versicolor  Species_virginica    scores  anomaly  
106                   0                  1 -0.008763       -1  
150                   0                  0 -0.287729       -1

pps score

In [ ]:
#install the package
!pip install ppscore

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import ppscore as pps

In [ ]:
#pps.score(df, "feature_column", "target_column")  syntax
pps.score(data, "Sepal.Length", "Petal.Length")

{'x': 'Sepal.Length',
 'y': 'Petal.Length',
 'ppscore': 0.550422595049248,
 'case': 'regression',
 'is_valid_score': True,
 'metric': 'mean absolute error',
 'baseline_score': 1.4886666666666668,
 'model_score': 0.6692708968366863,
 'model': DecisionTreeRegressor()}

In [ ]:
#calculate the whole PPS matrix
pps.matrix(data)

x             y   ppscore            case  is_valid_score  \
0   Sepal.Length  Sepal.Length  1.000000  predict_itself            True   
1   Sepal.Length   Sepal.Width  0.000000      regression            True   
2   Sepal.Length  Petal.Length  0.550423      regression            True   
3   Sepal.Length   Petal.Width  0.431739      regression            True   
4   Sepal.Length       Species  0.471649  classification            True   
5    Sepal.Width  Sepal.Length  0.006966      regression            True   
6    Sepal.Width   Sepal.Width  1.000000  predict_itself            True   
7    Sepal.Width  Petal.Length  0.172375      regression            True   
8    Sepal.Width   Petal.Width  0.132858      regression            True   
9    Sepal.Width       Species  0.156915  classification            True   
10  Petal.Length  Sepal.Length  0.525617      regression            True   
11  Petal.Length   Sepal.Width  0.052136      regression            True   
12  Petal.Length  Petal.Length  1.000000  predict_itself            True   
13  Petal.Length   Petal.Width  0.744945      regression            True   
14  Petal.Length       Species  0.884812  classification            True   
15   Petal.Width  Sepal.Length  0.383911      regression            True   
16   Petal.Width   Sepal.Width  0.254616      regression            True   
17   Petal.Width  Petal.Length  0.798274      regression            True   
18   Petal.Width   Petal.Width  1.000000  predict_itself            True   
19   Petal.Width       Species  0.927652  classification            True   
20       Species  Sepal.Length  0.409634      regression            True   
21       Species   Sepal.Width  0.194307      regression            True   
22       Species  Petal.Length  0.785393      regression            True   
23       Species   Petal.Width  0.755749      regression            True   
24       Species       Species  1.000000  predict_itself            True   

                 metric  baseline_score  model_score                     model  
0                  None        0.000000     1.000000                      None  
1   mean absolute error        0.330667     0.364704   DecisionTreeRegressor()  
2   mean absolute error        1.488667     0.669271   DecisionTreeRegressor()  
3   mean absolute error        0.644667     0.366339   DecisionTreeRegressor()  
4           weighted F1        0.353333     0.658333  DecisionTreeClassifier()  
5   mean absolute error        0.684667     0.679897   DecisionTreeRegressor()  
6                  None        0.000000     1.000000                      None  
7   mean absolute error        1.488667     1.232058   DecisionTreeRegressor()  
8   mean absolute error        0.644667     0.559017   DecisionTreeRegressor()  
9           weighted F1        0.353333     0.454805  DecisionTreeClassifier()  
10  mean absolute error        0.684667     0.324794   DecisionTreeRegressor()  
11  mean absolute error        0.330667     0.313427   DecisionTreeRegressor()  
12                 None        0.000000     1.000000                      None  
13  mean absolute error        0.644667     0.164425   DecisionTreeRegressor()  
14          weighted F1        0.353333     0.925512  DecisionTreeClassifier()  
15  mean absolute error        0.684667     0.421816   DecisionTreeRegressor()  
16  mean absolute error        0.330667     0.246474   DecisionTreeRegressor()  
17  mean absolute error        1.488667     0.300302   DecisionTreeRegressor()  
18                 None        0.000000     1.000000                      None  
19          weighted F1        0.353333     0.953215  DecisionTreeClassifier()  
20  mean absolute error        0.684667     0.404204   DecisionTreeRegressor()  
21  mean absolute error        0.330667     0.266416   DecisionTreeRegressor()  
22  mean absolute error        1.488667     0.319479   DecisionTreeRegressor()  
23  mean absolute error        0.644667     0.157460   DecisionTreeRegressor()  
24           